[블랙잭] 권순찬 미션 제출합니다.
econo-spring-2021/java-blackjack pull request #1
Opened 2021-07-15 04:50 UTC by Kwon770

테스트해야한다고 생각하는 메소드들은 전부 TDD로 구현하였는데도, method coverage가 35%수준이네요.. 어떤 메소드들에 대해 더 테스트 코드를 작성해야 할까요?

2021-07-15 04:58 UTC, Kwon770 commented
그리고 2가지 질문이 더 있습니다.. 
1. 테스트 코드는 하드 코딩으로 값을 작성해야 할까요? 플레이어가 카드를 더 뽑을지 말지를 판단하는 메소드를 테스트할때 든 생각인데, 값을 명시함으로써 테스트 코드를 작성한 경우 카드 값의 한계가 21에서 변경되면 테스트 코드가 변경되어야 할거라고 생각했습니다. 그래서 다음과 같이 다른 코드에 의존적으로 작성하였는데, 올바른 테스트 코드 일까요? 다른 코드에 의존적이다 보니, 문제가 발생했을때 테스트 코드도 잘못된 값에 의존하여 테스트될 것 같은 느낌입니다.
![스크린샷 2021-07-15 09 27 33](https://user-images.githubusercontent.com/49567744/125731054-44594af1-33ee-4919-b09e-44384a12c1ec.png)

2. `User.java` 의 30줄의 `getMoreCardTillUnableOrDeny` 함수에서 조건이 충족된 경우, 카드를 뽑기 위해 `Game.java`의 필드로 관리되고 있는 `CardPack.java`에 접근해서 메소드를 실행시켜야 하지만 접근할 방법이 떠오르지 않았습니다. 그래서 `Game.java` 의 70번줄처럼 필드를 매개변수로 넘겨줌으로서 메소드에 접근할 수 있도록 하였습니다. 올바르지 않은 방법으로 접근한듯한 느낌이 드는데 잘못된 방법일까요?

2021-07-18 15:41 UTC, hotheadfactory requested changes
1. 다른 클래스의 로직이 아닌 상수에 접근하기 때문에 그런 위험성은 낮을 것 같습니다.
2. 사실 `getMoreCardTillUnableOrDeny` 메소드는 User가 아닌 Game의 책임이어야 맞을 것 같습니다. 내부에서 호출하는 메소드가 전부 public이고, OutputView까지 호출하고 있네요.

> 딜러와 플레이어에서 발생하는 중복 코드를 제거해야 한다.
이 조건에 부합하도록 리팩토링 후, 다시 리뷰요청 해 주세요!
(힌트: 상속이나 인터페이스 구현을 이용해 보세요)

2021-07-18 15:41 UTC, hotheadfactory commented on src/main/java/blackjack/controller/gameController.java
> +public class GameController {
macOS에서 개발하실 때 주의해야 할 점으로서, **macOS의 APFS 파일 시스템은 대소문자 구분을 하지 않는다는 사실!** 을 항상 기억하고 있어야 합니다.
지금 이 클래스를 보면 java 파일의 이름은 `gameController` 지만, 그 안에 선언된 클래스 명은 `GameController` 입니다.
이 경우 macOS 상에서 돌려 보았을 때는 아무런 문제가 없지만, 리눅스를 사용하는 서버에 올라가게 되면
`java: class GameController is public, should be declared in a file named GameController.java`
와 같이 파일명과 클래스명이 일치하지 않는다는 에러를 내면서 컴파일이 되지 않습니다.
문제는 이런 실수를 알아차려서 파일명을 수정하려고 해도 macOS 시스템상 이전 파일명과 바뀐 파일명을 같은 것으로 인식하기 때문에... 이를 바로잡으려면 Git 저장소 디렉토리 내에서 `git config core.ignorecase false` 를 입력하시면 됩니다.

2021-07-20 12:50 UTC, hotheadfactory reviewed
지금 테스트한 클래스들을 보면 Card, Game, Input, User 4개 뿐이에요.
그 외에 나머지 클래스들을 테스트해 보는 게 어떨까요?

Test With Coverage를 돌린 다음에 코드에 표시되는 초록색/빨간색 띠로도 메소드/라인의 커버 여부를 확인할 수 있습니다 :)

2021-07-20 13:08 UTC, hotheadfactory requested changes

2021-07-20 13:08 UTC, hotheadfactory commented on src/main/java/blackjack/domain/CardPack.java
> +            randomShapeIdx = (int) Math.floor(Math.random() * 4);
지금 카드를 그때그때 랜덤으로 생성하는 것으로 보이는데, 이렇게 되면 중복된 카드가 나오지 않을까요?
실제 블랙잭 게임은 트럼프 카드 한 세트로 하기 때문에 카드가 중복될 일이 없습니다.
**카드를 미리 다 만들어놓고 섞은 다음, 한 장식 뽑아 쓰는 것** 은 어떨까요?

2021-07-20 13:08 UTC, hotheadfactory commented on src/main/java/blackjack/domain/CardPack.java
> +        } else if (idx == 13) {
카드의 숫자도 enum으로 관리해 보는 건 어떨까요?

2021-07-20 13:08 UTC, hotheadfactory commented on src/main/java/blackjack/domain/UserInfoDto.java
> +        if(isDrawer) {
boolean을 리턴하면 간단하지 않을까요?

2021-07-20 13:08 UTC, hotheadfactory commented on src/main/java/blackjack/domain/UserInfoDto.java
> +        if (opponentScore == score) {
DTO는 말 그대로 데이터를 전달하는 객체로서, 보통 로직은 DTO에 넣지 않습니다.

2021-07-21 05:56 UTC, Kwon770 commented
피드백에 따라 모두 수정하였습니다! 단, 아래에 관한 피드백은 재질문이 있습니다.

![스크린샷 2021-07-21 14 54 07](https://user-images.githubusercontent.com/49567744/126438212-aef71e25-83c7-49c4-a7e8-3de65f2c8325.png)

피드백해준 것과 같은 메소드의 경우, 해당 메소드가 사용되는 곳은 count를 세리는 곳에서 사용됩니다. 따라서 다음과 같이 함수를 만들지 않으면 사용되는 곳에서 별도의 if문을 사용해야 하므로, 깊이 1이 제약인 현 규칙에서 피할 수 없는 메소드로 보입니다. 혹시 다른 방법이 있을까요?

2021-08-01 07:01 UTC, hotheadfactory approved these changes
리뷰가 늦었네요ㅠㅠ 
수고하셨습니다!

2021-08-01 07:01 UTC, hotheadfactory commented on src/main/java/blackjack/domain/Card.java
> +    public int returnOneIfAceElseReturnZero() {
0 또는 1을 리턴하는 것은 충분히 명시적이지 못한 것 같습니다.

물론 `depth를 2 미만으로 줄인다` 같은 요구 사항도 중요하지만, 알아보기 쉬운 코드를 짜는 것이 더 중요합니다.
이 경우에는 그냥 depth를 2로 하고 true/false를 리턴하도록 바꿔 보세요.

2021-08-01 07:01 UTC, hotheadfactory commented on src/main/java/blackjack/controller/gameController.java
> +    public void revealInitCard(List<UserInfoDto> userInfoDtos, DealerInfoDto dealerRevealInfoDto) {
웬만하면 메소드명을 축약하지 않도록 노력해 주세요.
`revealInitialCards`는 어떨까요?

2021-08-01 07:01 UTC, hotheadfactory commented on src/main/java/blackjack/controller/GameController.java
> +public class GameController {
현재 `GameController`와 `gameController` 이렇게 2개가 존재하는 것으로 보입니다.

2021-08-01 07:04 UTC, merged