[블랙잭] 김송아 미션 제출합니다.
econo-spring-2021/java-blackjack pull request #2
Opened 2021-07-15 05:17 UTC by asong57

- 카드 부분에서 enum을 더 활용해보려고 했는데 숫자를 포함한 형태를 어떻게 enum으로 잘 활용할 수 있을지  잘 모르겠어서 카드의 Type만 enum으로 구현했습니다.
- A 카드의 계산에서 더 좋은 알고리즘으로 계산을 할 수 있을 것 같은데 잘 아직 떠오르지가 않네요..
- GameTest에서 askPlayersOneMoreCard 부분을 아직 테스트코드 작성을 못 했는데..흠 어떤 방식으로 이 메소드는 테스트 코드를 작성해야 할지 잘 감이 안 옵니다..

2021-07-20 14:18 UTC, hotheadfactory requested changes
1. 카드의 number도 enum으로 구현하고 싶으면 enum의 name을 `ONE, TWO, THREE...` 등으로 짓고 필드를 만들어 `1, 2, 3,...,J, Q, K` 등을 적어 두는 게 어떨까요?
2. A 카드의 점수 계산은 플레이어 입장에서 사실 거의 답정너인 문제에요. A를 제외한 다른 카드들의 점수 합산이 11 이상일 때 A를 11점으로 계산하여 버스트 되는 바보는 없을 것이고, 10 이하라면 무조건 11로 계산하여 21에 가깝도록 만들어 카드를 한 장 더 뽑음으로써 생기는 버스트의 위험을 줄이는 것이 합리적인 선택입니다.
즉 플레이어가 선택할 수 있도록 만드는 것도 좋겠지만, 지금 구현한 대로 자동 계산해도 무방합니다.
3. askPlayersOneMoreCard 가 OutputView를 호출하기 때문에 테스트하기는 어렵습니다. 다만 메소드를 분리하여 테스트하고 싶은 부분을 따로 떼어내 테스트하는 방법을 택할 수 있습니다.

2021-07-20 14:18 UTC, hotheadfactory commented on src/main/java/controller/Game.java
> +        for (Player player : players.getPlayers()) {
컬렉션에 대해서 Getter, Setter를 사용하는 것은 좋은 습관이 아닙니다. 컬렉션 내용이 밖에서 수정되면 객체 안의 컬렉션 내용도 같이 변경되기 때문이죠.
가급적 컬렉션을 밖으로 내지 말고 컬렉션을 가지고 있는 객체에 일을 시키는 것이 좋습니다.

2021-07-20 14:18 UTC, hotheadfactory commented on src/main/java/controller/Game.java
> +        Player dealer = players.getPlayers().get(0);
가장 첫번째로 들어간 플레이어를 딜러로 간주하게 되어 있는데, 
이렇게 하는 것 대신 플레이어를 생성하는 부분의 구현이 바뀌어도 이상이 없게끔 좀더 명시적으로 구현할 순 없을까요?
(힌트: 추상 클래스나 인터페이스를 이용하면 어떨까요?)

2021-08-03 12:34 UTC, asong57 commented on src/main/java/controller/Game.java
> +        for (Player player : players.getPlayers()) {
일급컬렉션의 Getter를 없애기 위해서 Controller의 Game 클래스에 존재하던 많은 메서드들을 컬렉션 Players에 많이 옮겼는데 괜찮은 걸까요? 컨트롤러의 기능이 많이 사라져버렸는데 괜찮은 건지 궁금합니다!
@hotheadfactory

2021-08-03 12:34 UTC, asong57 commented on src/main/java/controller/Game.java
> +        Player dealer = players.getPlayers().get(0);
이 부분은 2주차 미션에 녹여보겠습니다!

2021-08-05 17:15 UTC, hotheadfactory approved these changes
수고하셨습니다.
아래 피드백은 2주차에서 반영해 보세요.

2021-08-05 17:15 UTC, hotheadfactory commented on src/main/java/domain/Players.java
> +import view.InputView;
도메인이 직접 입력을 받고 있네요. 입출력을 호출하는 일은 Controller만 하도록 리팩토링할 수 있을까요?

2021-08-05 17:15 UTC, hotheadfactory commented on src/main/java/view/OutputView.java
> +            if (i != player.getCards().getCards().size() - 1) {
뎁스를 한번 줄여 보세요!

2021-08-05 17:15 UTC, hotheadfactory commented on src/main/java/domain/Cards.java
> +        return cards.remove(0);
컬렉션을 파라미터로 받아 수정하여 돌려주는 이와 같은 메소드는 객체의 캡슐화가 깨어지고 있다는 신호입니다.
cards를 가지고 있는 메소드에서 책임을 지도록 바꿔 보세요!

2021-08-05 17:15 UTC, hotheadfactory commented on src/main/java/domain/Players.java
> +            dealer.getCards().getCards().add(cards.giveCard(cards.getCards()));
이런 식으로 getCards()를 여러번 Chaining해서 쓰기보단, 이 행위를 가장 잘 설명할 수 있는 이름의 메소드를 하나 더 만드는 게 어떨까요?

2021-08-05 17:15 UTC, hotheadfactory commented on src/main/java/domain/Players.java
> +            while (answer.equals("y")) {
팁: String.equals를 사용할 때 `"y".equals(answer)` 식으로 상수에 대하여 사용하면 NullPointerException을 방지할 수 있습니다.

2021-08-12 11:37 UTC, asong57 commented
2주차 미션 완료했습니다!

2021-08-18 14:11 UTC, hotheadfactory requested changes
안녕하세요 송아님!
리뷰가 늦어서 죄송합니다ㅠㅠ
아래 내용 고민해 보시고 다시 리뷰요청 해주세요!

2021-08-18 14:11 UTC, hotheadfactory commented on src/main/java/controller/Game.java
> +        for (int i = 1; i < players.getPlayersSize(); i++) {
인덱스 0에 위치하는 딜러를 제외하고 나머지 플레이어에게 베팅 금액을 묻는 코드인데요,
코드를 처음 보는 사람 입장이라면 이 코드를 보고 무엇을 의미하는지 바로 이해하기 어려울 것 같습니다. 
다른 방법이 없을지 생각해 보세요!

2021-08-18 14:11 UTC, hotheadfactory commented on src/main/java/domain/Card.java
> +    public enum Type {
enum을 이너 클래스로 선언하기보다 별도 파일로 분리하는 것이 좋지 않을까요?
number도 모든 String이 들어갈 수 있는 값이 아닌 2~10, A, K, Q, J로 제한해야 하므로 enum화 시키는 게 좋지 않을까요?

2021-08-18 14:11 UTC, hotheadfactory commented on src/main/java/controller/Game.java
> +            players.add(new Player("딜러"));
딜러를 단순히 "딜러"란 이름을 가진 플레이어로 넣기보다, 구조상으로 완전히 다르게 구분하는 게 어떨까요? Player를 상속한 Dealer 클래스를 만드는 것이 한 방법일 수 있습니다.

2021-08-18 14:11 UTC, hotheadfactory commented on src/main/java/Application.java
> +        Game.setPlayersBettingMoney(players);
Game.play() 하면 Game이 게임 전 과정의 흐름을 알아서 제어하게 만드는 건 어떨까요?

2021-08-18 14:11 UTC, hotheadfactory commented on src/test/java/PlayersTest.java
> +public class PlayersTest {
오류 상황에 대한 테스트도 작성해 주세요!

2021-10-07 11:48 UTC, merged